name: Reuse deployment Workflow

on:
  workflow_call:
    inputs:
      mongo_uri:
        required: true
        type: string


    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true


jobs:
  reuse-deployment:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://${{ steps.set-app-ingress-host-url.outputs.URL }}

    outputs:
      URL: ${{ steps.set-app-ingress-host-url.outputs.URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Setup kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-kubeconfig }}

      - name: Fetch kubernetes cluster details
        run: |
          kubectl version --short
          kubectl cluster-info
          echo ---------------------------------
          kubectl get nodes
          echo ---------------------------------

      - name: Save Nginx ingress controller ip as a github env variable
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace token in manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: create mongodb secret in kubernetes
        run: |
          kubectl create secret generic mongo-secret \
            --from-literal=MONGO_URI="${{ inputs.MONGO_URI }}" \
            --from-literal=MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \
            --from-literal=MONGO_PASSWORD="${{ secrets.mongodb-password }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to development environment
        run: |
          kubectl apply -f kubernetes/development/

      - name: set app ingress host url
        id: set-app-ingress-host-url
        run: |
          URL=$(kubectl -n ingress-nginx get ingress solar-system-ingress -o jsonpath='{.spec.rules[0].host}')
          echo "URL=$URL" >> $GITHUB_OUTPUT
