name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: mongodb+srv://${{ vars.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD }}@supercluster.d83jj.mongodb.net/superData?retryWrites=true&w=majority
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
            env:
              MONGO_URI: 'mongodb://localhost:27017/superData'
              MONGO_USERNAME: non-prod-user #Striclty for testing purpose, not to be used in production
              MONGO_PASSWORD: non-prod-password #Always use secrets for sensitive data, this is just for testing purpose
        strategy:
          matrix:
            nodejsversion: [18,20]
            # operating-system: [ubuntu-latest, macos-latest]
            operating-system: [ubuntu-latest]
            # exclude:
            #   - nodejsversion: [18,20]
            #     operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejsversion }}

        - name: Cache NPM Dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-testing-step
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v6
          with:
            name: Mocha-Test-Result-${{ matrix.nodejsversion }}-${{ matrix.operating-system }}
            path: test-results.xml
            retention-days: 1

    code-coverage:
      name: Code Coverage
      # needs: unit-testing
      runs-on: ubuntu-latest
      container:
        image: node:18
      services:
        mongo-db:
          image: siddharth67/mongo-db:non-prod
          options:
            --name mongo
          ports:
            - 27017:27017
          env:
            MONGO_URI: 'mongodb://mongo:27017/superData'
            MONGO_USERNAME: non-prod-user #Striclty for testing purpose, not to be used in production
            MONGO_PASSWORD: non-prod-password #Always use secrets for sensitive data, this is just for testing purpose
      continue-on-error: true
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup NodeJS Version
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      
      - name: Install Dependencies
        run: npm install

      - name: Run Code Coverage
        run: npm run coverage
        continue-on-error: true

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: Code-Coverage-Result-${{ matrix.nodejsversion }}-${{ matrix.operating-system }}
          path: coverage
          retention-days: 1

    docker:
      name: Containerization
      permissions:
        contents: read
        packages: write
      runs-on: ubuntu-latest
      needs: [unit-testing, code-coverage]
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build for testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
          
      - name: Docker image testing
        run: |
          docker run --name solar-system-app -d \
            -p 3000:3000 \
            -e MONGO_URI="$MONGO_URI" \
            -e MONGO_USERNAME="$MONGO_USERNAME" \
            -e MONGO_PASSWORD="$MONGO_PASSWORD" \
            ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo "Container IP: $IP"

          echo "Testing image url using wget"
          sleep 5
          wget -q -O - http://127.0.0.1:3000/live || echo "Health check failed"

      - name: Docker push for testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
      
    dev-deployment:
      needs: docker
      runs-on: ubuntu-latest
      environment:
        name: development
        url: https://${{ steps.set-app-ingress-host-url.outputs.URL }}
      outputs:
        URL: ${{ steps.set-app-ingress-host-url.outputs.URL }}
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Setup kuebconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }} #Currently Dont have kubeconfig
        continue-on-error: true

      - name: Fetch kubernetes cluster details
        run: |
          kubectl version --short
          kubectl cluster-info
          echo ---------------------------------
          kubectl get nodes
          echo ---------------------------------
        continue-on-error: true

      - name: Save Nginx ingress controller ip as a github env variable
        run: |
          echo "INGRESS-IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace token in manifest files
        uses: cschleiden/replace-token-action@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ secrets}}
          INGRESS_IP: ${{ env.INGRESS-IP }}

      - name: create mongodb secret in kubernetes
        run: |
          kubectl create secret generic mongo-secret \
            --from-literal=MONGO_URI="${{ env.MONGO_URI }}" \
            --from-literal=MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \
            --from-literal=MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            --save-config
            --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy to development environment
        run: |
          kubectl apply -f kubernetes/development/

      - name: set app ingress host url
        id: set-app-ingress-host-url
        run: |
          URL=$(kubectl -n ingress-nginx get ingress solar-system-ingress -o jsonpath='{.spec.rules[0].host}')
          echo "URL=$URL" >> $GITHUB_OUTPUT

    integration-testing:
      name: Integration Testing
      needs: dev-deployment
      runs-on: ubuntu-latest
      steps:
      - name: Test URL output using curl and jq
        env:
          URL: ${{ needs.dev-deployment.outputs.URL }}
        run: |
          echo $URL
          echo "------------------------------"
          curl -s http://$URL/live -s -k | jq -r .status | grep -i live || echo "Integration test failed"